### ISSUE TITLE
Mateus Cardoso Nunes

### ISSUE THREAD

**Issue by mateusdeveloper** [suiteplus/recruitment#2]
https://github.com/mateusdeveloper/SystemMonitorMachine.git

**Comment by michelpm1** [comment]
[https://github.com/michelpm1/transportapp](https://github.com/michelpm1/transportapp)

**Comment by danieljoppi** [comment]
### SytemMonitorMachine
Gostei da implementação, bem simples e pratica.

## Segunda Etapa de Implementações

Para segunda etapa tu deves criar um projeto `node.js`, usando `gulp` para gerenciar o projeto.
- Utilizar algum gerenciador de pacotes, como o `npm`;
- Faça a  documentação do código no padrão do `jsdoc`.


Nesse projeto tu tem que:

- *cron*: Buscar todos os Deputados Federais periodicamente. Ver [Site Deputados Federais](http://www2.camara.leg.br/deputados/pesquisa).
   - sugestão: veja [request](https://github.com/request/request) para fazer o download do HTML.
- *cron*: Fazer o parse das informações apresentadas no site, e gerar um JSON com dados.
   - sugestão: veja [jsdom](https://github.com/tmpvar/jsdom) se quiser interpretar o HTML.
- *server*: enviar o JSON com o dados para um REST no teu servidor e armazena-lo no `mongodb`.
   - POST - http://localhost:3000/api/data
   - o JSON deve ser enviado no BODY da requisição.
   - use [express](https://github.com/expressjs/express) ou [restify](https://github.com/restify/node-restify) para montar o servidor rest

Exemplo da estrutura do JSON esperada: 
```javascript
[
  {
        "fullName": "Nome do Deputado, ex: João da Silva",
        "birthday": "Data de aniversário, formato  DD-MM",
        "party": "Sigla do Partido, ex: PJS",
        "state": "Sigla do Estado do Depudado, ex: SC",
        "main": "Se for Titular 'true', senão false ou null",
        "phone": "Telefone do Deputado Federal",
      // use a criatividade para organizar os outros dados.
  }
]
```

Diferenciais desse projeto é a quantidade de informações que vocês consegue buscar sobre um deputado:
 -  Buscar somente as **Informações do Deputado** e o **Endereço para correspondência**, não fez mais que o básico :+1: ;
 - Se bucar as **Minhas informações na Câmara** já tem um diferencial nas informações :star: ;
 - Se conseguir relacionar as informações do deputado a outro site (Facebook, LinkedIn, etc...) e complementar ainda mais o levantamento de dados, isso é além do esperado :star2: :star2: :star2:.

Outros extras:

- [ ] Implementação de teste unitário usando [mocha](https://github.com/mochajs/mocha).
- [ ] Fazer a Análise de cobertura de código usando [istanbul](https://github.com/gotwarlost/istanbul).
- [ ] Criar gerenciador do projeto no [gulp](https://github.com/gulpjs/gulp).
- [ ] Integrar os testes do Projeto com o [travis-ci](https://travis-ci.org/).
- [ ] Integrar a cobertura de testes do Projeto com o [coveralls](https://coveralls.io/).

Prazo final normal é dia 18/05/2016, depois disso começa a perder pontos - Qualquer dúvida pode entrar em contato pelo email: daniel.joppi@suiteplus.com

**Comment by danieljoppi** [comment]
obs: data é 18/03 e não 18/05

**Comment by michelpm1** [comment]
Olá boa noite, estou tentando pelo request
<https://github.com/request/request#examples> sugestão de vocês para buscar
as informações, mas parece existir algum bloqueio, gostaria de informar que
também não consigo ver as informações dos deputados (da um erro) caso eu
selecione a opção qualquer legislatura, apenas é possível visualizar as
informações dos atuais 2015-2019.

Console.log do body (utilizando o request para a página html com os
deputados de 2015.2019)
"
<p>Nossos sistemas autom&aacute;ticos de seguran&ccedil;a impediram que a
opera&ccedil;&atilde;o fosse conclu&iacute;da.<p>
                <p>Isso pode ocorrer quando voc&ecirc; copia dados de
outros sites e eles v&ecirc;m com conte&uacute;dos n&atilde;o permitidos.<p>
                <p>Voc&ecirc; pode <a href="javascript:history.back()"
title="voltar...">voltar</a>, revisar o que estava fazendo e tentar
novamente.<p>
"



2016-03-10 15:07 GMT-03:00 Daniel Henrique Joppi <notifications@github.com>:

**Comment by michelpm1** [comment]
Acabei de verificar que não são todos que da o erro selecionando qualquer
legislatura, apenas alguns.



Em 10 de março de 2016 20:52, Michel Machado <michelpm1@gmail.com> escreveu:

**Comment by danieljoppi** [comment]
Parece mais problema no site deles ... Pega o que der ... Não tem problema
se não vir tudo ... O interessante é que teu algoritmo seja flexível para
não parar nesses caso e seguir em frente ... E depois de um tempo voltar e
tentar de novo ...

**Comment by michelpm1** [comment]
S mas não consigo pegar nada

da este erro na página geral com os deputados quando tempo buscar com o
request ou quando tempo um deputado isolado

(resultado no body do request)
<p>Nossos sistemas autom&aacute;ticos de seguran&ccedil;a impediram que a
opera&ccedil;&atilde;o fosse conclu&iacute;da.<p>
                <p>Isso pode ocorrer quando voc&ecirc; copia dados de
outros sites e eles v&ecirc;m com conte&uacute;dos n&atilde;o permitidos.<p>
                <p>Voc&ecirc; pode <a href="javascript:history.back()"
title="voltar...">voltar</a>, revisar o que estava fazendo e tentar
novamente.<p>
"

Em 10 de março de 2016 23:17, Daniel Henrique Joppi <
notifications@github.com> escreveu:

**Comment by danieljoppi** [comment]
Vai precisar mudar o `User-Agent` nos teus request para de de um Browser valido.

Da uma olhada aqui: https://github.com/request/request#custom-http-headers

`'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36'`
