### ISSUE TITLE
Michel Machado

### ISSUE THREAD

**Issue by michelpm1** [suiteplus/recruitment#3]
[https://github.com/michelpm1/transportapp](https://github.com/michelpm1/transportapp)

**Comment by danieljoppi** [comment]
### transportapp
Gostei da implementação, bem simples e pratica.

Sugestões pro projeto:
- Utilizar algum gerenciador de pacotes, como: `npm` ou `bower`;
- Teu código ficou padronizado, e você poderia complementar ele com `jslint` ou `eslint`, um extra;
- Faltou documentação do código, olhe o padrão de `jsdoc`.

## Segunda Etapa de Implementações

De uma lida na bibliotecar mencionadas acima e tente aplica-las nesse projeto.

Para segunda etapa tu deves criar um projeto `node.js`, usando `gulp` para gerenciar o projeto, nele tu tem que:

- *cron*: Buscar todos os Deputados Federais periodicamente. Ver [Site Deputados Federais](http://www2.camara.leg.br/deputados/pesquisa).
   - sugestão: veja [request](https://github.com/request/request) para fazer o download do HTML.
- *cron*: Fazer o parse das informações apresentadas no site, e gerar um JSON com dados.
   - sugestão: veja [jsdom](https://github.com/tmpvar/jsdom) se quiser interpretar o HTML.
- *server*: enviar o JSON com o dados para um REST no teu servidor e armazena-lo no `mongodb`.
   - POST - http://localhost:3000/api/data
   - o JSON deve ser enviado no BODY da requisição.
   - use [express](https://github.com/expressjs/express) ou [restify](https://github.com/restify/node-restify) para montar o servidor rest

Exemplo da estrutura do JSON esperada: 
```javascript
[
  {
        "fullName": "Nome do Deputado, ex: João da Silva",
        "birthday": "Data de aniversário, formato  DD-MM",
        "party": "Sigla do Partido, ex: PJS",
        "state": "Sigla do Estado do Depudado, ex: SC",
        "main": "Se for Titular 'true', senão false ou null",
        "phone": "Telefone do Deputado Federal",
      // use a criatividade para organizar os outros dados.
  }
]
```

Diferenciais desse projeto é a quantidade de informações que vocês consegue buscar sobre um deputado:
 -  Buscar somente as **Informações do Deputado** e o **Endereço para correspondência**, não fez mais que o básico :+1: ;
 - Se bucar as **Minhas informações na Câmara** já tem um diferencial nas informações :star: ;
 - Se conseguir relacionar as informações do deputado a outro site (Facebook, LinkedIn, etc...) e complementar ainda mais o levantamento de dados, isso é além do esperado :star2: :star2: :star2:.

Outros extras:

- [ ] Implementação de teste unitário usando [mocha](https://github.com/mochajs/mocha).
- [ ] Fazer a Análise de cobertura de código usando [istanbul](https://github.com/gotwarlost/istanbul).
- [ ] Criar gerenciador do projeto no [gulp](https://github.com/gulpjs/gulp).
- [ ] Integrar os testes do Projeto com o [travis-ci](https://travis-ci.org/).
- [ ] Integrar a cobertura de testes do Projeto com o [coveralls](https://coveralls.io/).

Prazo final normal é dia 18/05/2016, depois disso começa a perder pontos - Qualquer dúvida pode entrar em contato pelo email: daniel.joppi@suiteplus.com

**Comment by michelpm1** [comment]
Olá boa tarde Daniel, que bom que gostou do App, então estive lendo sobre a
segunda etapa, e preciso verificar algumas coisas com você.

No momento eu estou procurando outras oportunidades também, e o prazo de 2
meses é um pouco complicado para mim, pois é provável que surjam outras
oportunidades no meio tempo, sem contar que no momento eu já estou
realizando outro teste, pelo que vi você também quer algo meu em backend,
(eu tinha dúvidas quanto a qual projeto meu enviar pois o outro em backend
foi feito com o meanjs stack http://meanjs.org/ e não tinha certeza se lhes
interessa) mas aqui está o link https://github.com/michelpm1/meanProject aqui
tem uma demo dele live https://immense-wildwood-5257.herokuapp.com/

Estou também em dúvidas sobre o nível do cargo pretendido(não tem esta
informação no site de vocês) eu faço esta pergunta pois já me aconteceu de
eu criar um projeto para no final dele a empresa descartar a possibilidade
comigo informando que estavam em busca de um perfil mais senior.

Gostaria de falar um pouco sobre o que pretendo também se ainda existir o
interesse, minha pretenção é entre 2200,00 - 3000,00.


Eu não conheço algumas tecnologias que foram socilitadas como (coveralls,
travis-ci), pois até então não me foi necessário o que é normal, porém nada
que uma pesquisa e ver alguns exemplos de uso não resolvam "essa é a vida
de programador não é?".

Seria interessante para mim realizar o teste em 2 semanas ou menos mas não
ele todo(eu estou bem afim de fazer tudo mas o tempo óoo..), posso realizar
até o básico informado, e podemos se você quiser dar continuidade no
processo seletivo (entrevistas etc), e continuo enviando requests para o
git com o resto do teste.


Quero muito trabalhar com essas tecnologias que são o que há de mais novo
no mercado e a empresa de vocês as usam, espero que possamos continuar vai
ser um prazer.

Desde já Michel Machado.







Em 9 de março de 2016 13:02, Daniel Henrique Joppi <notifications@github.com

**Comment by evertonamorim** [comment]
Boa tarde Michel!

Algumas considerações:

- O prazo é 18/03, o Daniel se equivocou.
- Não há restrições quanto ao nível, buscamos pessoas que já conheçam estas tecnologias ou que tenham interesse em aprender por si só.
- Sua pretenção está dentro do que a vaga oferece, na próxima fase (entrevista presencial) chegamos a esta negociação.
- O não conhecer e buscar estes conhecimentos também fazem parte do processo seletivo.
- Conforme descrito, há um "básico" a ser feito, os demais itens são diferenciais seus em relação aos demais candidatos.
- É importante também você concluir o processo no Enliz, acredito que esteja faltando o vídeo de apresentação, não requer nenhum efeito especial ou cenário, é algo rápido, siga o script que fica fácil, este processo é necessário para aprovação do RH da empresa.
- Qualquer dúvida utilize os e-mails mencionados em https://github.com/suiteplus/recruitment para sanar.

Bom trabalho, aguardamos seu retorno.
Éverton Amorim

**Comment by michelpm1** [comment]
Certo então Éverton, estarei realizando o video e o teste no decorrer da
 semana.

Em 9 de março de 2016 17:39, Everton Amorim <notifications@github.com>
escreveu:
