### ISSUE TITLE
Karan Alves Pereira

### ISSUE THREAD

**Issue by karanalpe** [suiteplus/recruitment#4]
https://github.com/karanalpe/generic-documents
https://github.com/karanalpe/dynamic-components-json
https://github.com/karanalpe/android-game

**Comment by danieljoppi** [comment]
### android-game
Não tem códigos em *JavaScript*, só compilado Java (`class`).

### generic-documents
Não tem código em *JavaScript*, é um exemplo de JSF.

### dynamic-components-json
É em *JavaScript*, mas:

- Os códigos do projeto estão misturados aos das bibliotecas, nesse caso eu sugiro utilizar algum gerenciador de pacotes, como: `npm` ou `bower`;
- Teu código não ficou padronizado, ora usa `tab` e outra usa `espace`, nesse caso sugiro que olhe: `jslint` ou `eslint`;
- Faltou documentação do código, olhe o padrão de `jsdoc`.

## Segunda Etapa de Implementações

De uma lida na bibliotecar mencionadas acima e tente aplica-las nesse projeto.

Para segunda etapa tu deves criar um projeto `node.js`, usando `gulp` para gerenciar o projeto, nele tu tem que:

- *cron*: Buscar todos os Deputados Federais periodicamente. Ver [Site Deputados Federais](http://www2.camara.leg.br/deputados/pesquisa).
   - sugestão: veja [request](https://github.com/request/request) para fazer o download do HTML.
- *cron*: Fazer o parse das informações apresentadas no site, e gerar um JSON com dados.
   - sugestão: veja [jsdom](https://github.com/tmpvar/jsdom) se quiser interpretar o HTML.
- *server*: enviar o JSON com o dados para um REST no teu servidor e armazena-lo no `mongodb`.
   - POST - http://localhost:3000/api/data
   - o JSON deve ser enviado no BODY da requisição.
   - use [express](https://github.com/expressjs/express) ou [restify](https://github.com/restify/node-restify) para montar o servidor rest

Exemplo da estrutura do JSON esperada: 
```javascript
[
  {
        "fullName": "Nome do Deputado, ex: João da Silva",
        "birthday": "Data de aniversário, formato  DD-MM",
        "party": "Sigla do Partido, ex: PJS",
        "state": "Sigla do Estado do Depudado, ex: SC",
        "main": "Se for Titular 'true', senão false ou null",
        "phone": "Telefone do Deputado Federal",
      // use a criatividade para organizar os outros dados.
  }
]
```

Diferenciais desse projeto é a quantidade de informações que vocês consegue buscar sobre um deputado:
 -  Buscar somente as **Informações do Deputado** e o **Endereço para correspondência**, não fez mais que o básico :+1: ;
 - Se bucar as **Minhas informações na Câmara** já tem um diferencial nas informações :star: ;
 - Se conseguir relacionar as informações do deputado a outro site (Facebook, LinkedIn, etc...) e complementar ainda mais o levantamento de dados, isso é além do esperado :star2: :star2: :star2:.

Outros extras:

- [ ] Implementação de teste unitário usando [mocha](https://github.com/mochajs/mocha).
- [ ] Fazer a Análise de cobertura de código usando [istanbul](https://github.com/gotwarlost/istanbul).
- [ ] Criar gerenciador do projeto no [gulp](https://github.com/gulpjs/gulp).
- [ ] Integrar os testes do Projeto com o [travis-ci](https://travis-ci.org/).
- [ ] Integrar a cobertura de testes do Projeto com o [coveralls](https://coveralls.io/).

Prazo final normal é dia 18/05/2016, depois disso começa a perder pontos - Qualquer dúvida pode entrar em contato pelo email: daniel.joppi@suiteplus.com

**Comment by danieljoppi** [comment]
obs: data é 18/03 e não 18/05

**Comment by danieljoppi** [comment]
Vai precisar mudar o `User-Agent` nos teus request para de de um Browser valido.

Da uma olhada aqui: https://github.com/request/request#custom-http-headers

`'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36'`
